In [8]:
from transformers import BertTokenizerFast

In [10]:
tok = BertTokenizerFast.from_pretrained('bert-base-chinese')

In [11]:
sent = [
    ['中华人民共和国', '数字经济'],
    ['中华人民共和国国', '数字经济济'],
]

In [15]:
res = tok(sent, padding=True, return_tensors='pt', return_offsets_mapping=True)

In [17]:
res['offset_mapping']

tensor([[[0, 0],
         [0, 1],
         [1, 2],
         [2, 3],
         [3, 4],
         [4, 5],
         [5, 6],
         [6, 7],
         [0, 0],
         [0, 1],
         [1, 2],
         [2, 3],
         [3, 4],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1],
         [1, 2],
         [2, 3],
         [3, 4],
         [4, 5],
         [5, 6],
         [6, 7],
         [7, 8],
         [0, 0],
         [0, 1],
         [1, 2],
         [2, 3],
         [3, 4],
         [4, 5],
         [0, 0]]])

In [16]:
[[list(x) for x in offset] for offset in res["offset_mapping"]]

[[[tensor(0), tensor(0)],
  [tensor(0), tensor(1)],
  [tensor(1), tensor(2)],
  [tensor(2), tensor(3)],
  [tensor(3), tensor(4)],
  [tensor(4), tensor(5)],
  [tensor(5), tensor(6)],
  [tensor(6), tensor(7)],
  [tensor(0), tensor(0)],
  [tensor(0), tensor(1)],
  [tensor(1), tensor(2)],
  [tensor(2), tensor(3)],
  [tensor(3), tensor(4)],
  [tensor(0), tensor(0)],
  [tensor(0), tensor(0)],
  [tensor(0), tensor(0)]],
 [[tensor(0), tensor(0)],
  [tensor(0), tensor(1)],
  [tensor(1), tensor(2)],
  [tensor(2), tensor(3)],
  [tensor(3), tensor(4)],
  [tensor(4), tensor(5)],
  [tensor(5), tensor(6)],
  [tensor(6), tensor(7)],
  [tensor(7), tensor(8)],
  [tensor(0), tensor(0)],
  [tensor(0), tensor(1)],
  [tensor(1), tensor(2)],
  [tensor(2), tensor(3)],
  [tensor(3), tensor(4)],
  [tensor(4), tensor(5)],
  [tensor(0), tensor(0)]]]

In [ ]:
import torch

In [29]:
a = torch.randn(2,5)
a

tensor([[-1.0187, -0.7488, -1.2407, -0.3034,  0.2790],
        [ 2.4478,  0.5138, -0.0330,  0.2036,  0.6374]])

In [31]:
a>0

tensor([[False, False, False, False,  True],
        [ True,  True, False,  True,  True]])